import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Layout from '../components/Layout'
import Hero from '../components/Hero'
import Webdev from '../components/webdev'
import Cards from '../components/Cards'
import ReactSection from '../components/ReactSection'
import Work from '../components/Work'
import Idea from '../components/Idea'
import Testimonials from '../components/Testimonials'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <html lang="en"></html>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/example.png" />
      </Head>

      <Layout>
        <Hero />
        <Webdev />
        <ReactSection />
        <Cards />
        <Work />
        <Idea />
        <Testimonials />
      </Layout>
    </div>
  )
}
